openapi: 3.1.1
info:
  title: Inventory Microservice API - Fluffy Plushies Webshop
  version: "1.0.0"
  description: API to manage inventory items for the Fluffy Plushies Webshop.
servers:
  - url: http://localhost:8082/inventory
paths:
  /items:
    get:
      summary: Retrieve all items
      responses:
        '200':
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemResponseDto'
    post:
      parameters:
      - $ref: '#/components/parameters/TokenHeader'
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequestDto'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '400':
          description: Invalid input
  /items/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retrieve item details
      responses:
        '200':
          description: Item details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '404':
          description: Item not found
    patch:
      parameters:
      - $ref: '#/components/parameters/TokenHeader'
      summary: Update item details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequestDto'
      responses:
        '200':
          description: Item updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '400':
          description: Invalid input
        '404':
          description: Item not found
    delete:
      parameters:
      - $ref: '#/components/parameters/TokenHeader'
      summary: Delete an item
      responses:
        '204':
          description: Item deleted
        '404':
          description: Item not found
components:
  parameters:
    TokenHeader:
      in: header
      name: token
      description: Authentication token.
      required: true
      schema:
        type: string
        format: token
  schemas:
    ItemRequestDto:
      type: object
      properties:
        name:
          type: string
          example: "Fluffy Bear"
        imgLink:
          type: string
          format: uri
          example: "http://example.com/images/fluffy-bear.jpg"
        price:
          type: number
          format: float
          example: 29.99
        stock:
          type: integer
          description: "Number of items available in stock"
          example: 50
        details:
          allOf:
            - $ref: "#/components/schemas/ItemDetails"
            - type: object
      required:
        - name
        - imgLink
        - price
        - stock
        - details
    ItemResponseDto:
      allOf:
        - $ref: "#/components/schemas/ItemRequestDto"
        - type: object
          required:
            - id
      properties:
        id:
          type: string
          readOnly: true
          example: "item123"
    ItemDetails:
      type: object
      properties:
        description:
          type: string
          example: "A soft and cuddly plush bear."
        ageGroup:
          type: string
          description: "Recommended age group (e.g., '3+', '6+', etc.)"
          example: "3+"
        item_type:
          type: string
          description: "Type or category of the item"
          example: "Bears"
        material:
          type: string
          description: "Material composition of the item"
          example: "Plush fabric"
      required:
        - description
        - ageGroup
        - item_type
        - material
